-- AlterTable
ALTER TABLE "Event" ALTER COLUMN "startDatetime" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "endDatetime" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "saleStartTime" SET DATA TYPE TIMESTAMP(3);
